const CONFIG = {
    STUDENT_PROFILE_ENDPOINT: import.meta.env.VITE_STUDENT_PROFILE_ENDPOINT,
    STUDENT_COURSE_ENDPOINT: import.meta.env.VITE_STUDENT_COURSE_ENDPOINT ,
    STUDENT_COLLEGE_ENDPOINT: import.meta.env.VITE_STUDENT_COLLEGE_ENDPOINT,
    STUDENT_PICTURE_ENDPOINT: import.meta.env.VITE_STUDENT_PICTURE_ENDPOINT,
    LOGIN_ENDPOINT: import.meta.env.VITE_LOGIN_ENDPOINT ,
    LOGOUT_ENDPOINT: import.meta.env.VITE_LOGOUT_ENDPOINT ,
    API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
};

export default CONFIG;
