const CONFIG = {
    STUDENT_PROFILE_ENDPOINT: import.meta.env.VITE_STUDENT_PROFILE_ENDPOINT,
    STUDENT_COURSE_ENDPOINT: import.meta.env.VITE_STUDENT_COURSE_ENDPOINT ,
    STUDENT_COLLEGE_ENDPOINT: import.meta.env.VITE_STUDENT_COLLEGE_ENDPOINT,
    LOGIN_ENDPOINT: import.meta.env.VITE_LOGIN_ENDPOINT ,
    LOGOUT_ENDPOINT: import.meta.env.VITE_LOGOUT_ENDPOINT ,
};

export default CONFIG;
